### ISSUE TITLE
Got this error in Arch Linux with KDE environment

### ISSUE THREAD

**Issue by TheLoving** [derkomai/NordIndicator#1]
```
Traceback (most recent call last):

File "/home/TheLoving/Downloads/GitApps/NordIndicator/NordIndicator.py", line 250, in <module>
    handler = InstallationHandler()
  File "/home/TheLoving/Downloads/GitApps/NordIndicator/NordIndicator.py", line 179, in __init__
    self.icons = [f for f in os.listdir(self.srcIconDir) if f.endswith('.png')]
FileNotFoundError: [Errno 2] No such file or directory: '/icons'
```

I am using Arch Linux with KDE, have installed GTK2 and GTK3 modules.

**Comment by dvilelaf** [comment]
It seems the program does not find the icons folder. Where did you execute the script from? Is there an "icons" directory next to it?

**Comment by TheLoving** [comment]
I cloned this repo into Downloads folder, actual path is ```/home/TheLoving/Downloads/GitApps/```

**Comment by dvilelaf** [comment]
Ok. And what was the exact command you ran? I think there could be some bug with the script location detection.

**Comment by TheLoving** [comment]
Here it is

```python3 NordIndicator.py install``` root folder of this repo.

**Comment by dvilelaf** [comment]
Nice, thanks! Could you create an empty python script on that directory? Name it `test.py` or whatever, write these two lines inside:

```
import os
print(f'>{os.path.realpath(__file__)}<')
```
and run it like 

`python3 test.py`

Then paste here the printed value. That should print the path to the script between >< symbols.

**Comment by TheLoving** [comment]
Here it is

```>/home/TheLoving/Downloads/GitApps/NordIndicator/test.py<
```

**Comment by TheLoving** [comment]
Here it is

`>/home/TheLoving/Downloads/GitApps/NordIndicator/test.py<`

**Comment by dvilelaf** [comment]
Ok, I just uploaded a new version with a fix (but I am not 100% sure the bug I found is your problem). Can you try with the new one?

**Comment by TheLoving** [comment]
Still I get this error

Traceback (most recent call last):

```
  File "/home/TheLoving/Downloads/GitApps/NordIndicator/NordIndicator.py", line 250, in <module>
    handler = InstallationHandler()
  File "/home/TheLoving/Downloads/GitApps/NordIndicator/NordIndicator.py", line 179, in __init__
    self.icons = [f for f in os.listdir(self.srcIconDir) if f.endswith('.png')]
NotADirectoryError: [Errno 20] Not a directory: '/home/TheLoving/Downloads/GitApps/NordIndicator/NordIndicator.py/icons'
```

**Comment by TheLoving** [comment]
Here is the SS of the repo folder I have.
![Screenshot_20210623_224105](https://user-images.githubusercontent.com/81813176/123139796-370fa880-d474-11eb-8c79-d43170cac0d6.png)

**Comment by dvilelaf** [comment]
It seems the script name gets in the middle of the icon directory path, but I can't figure what's the difference between your system and mine. Could you try another python script with these lines and paste the result?

```
import os
import getpass

appName = __file__.replace('.py', '')
homeDir = f'/home/{getpass.getuser()}'
srcDir = os.path.realpath(__file__).replace(f'/{__file__}', '')
srcIconDir = f'{srcDir}/icons'

print(f'file: {__file__}\nappName: {appName}\nhomeDir: {homeDir}\nsrcDir: {srcDir}\nsrcIconDir: {srcIconDir}')
```

**Comment by TheLoving** [comment]
Here is the output:

```
file: /home/TheLoving/Downloads/GitApps/NordIndicator/test.py
appName: /home/TheLoving/Downloads/GitApps/NordIndicator/test
homeDir: /home/TheLoving
srcDir: /home/TheLoving/Downloads/GitApps/NordIndicator/test.py
srcIconDir: /home/TheLoving/Downloads/GitApps/NordIndicator/test.py/icons
```

**Comment by dvilelaf** [comment]
Ok, I think I see the problem. I'll try to fix it later and I will let you know. Thank you!

**Comment by TheLoving** [comment]
ok. I will wait until then.

**Comment by TheLoving** [comment]
Have you seen the error.

Check clearly it says `NordIndicator.py/icons`

The py file is checking for icons folder inside the NordIndicator.py (which is a python file and not a directory).

**Comment by dvilelaf** [comment]
Yes, I had already seen that. I found a bug with how I used the `__file__`  python variable. Sometimes is a relative path, sometimes absolute. I've just pushed some changes, let's see if it works now or where's the next error.

**Comment by TheLoving** [comment]
It did complete without error. But how to add that to KDE Panel?

Edit: It is not showing in widgets.

**Comment by dvilelaf** [comment]
It's been years since the last time I used KDE, but you sure have some app search bar inside the main KDE panel. Try searching "VPN" or "NordIndicator". Also, the indicator should start on reboot.

Although since it is using GTK it may not work in KDE, now that I think of it. I'm not sure. I'll have a look into it when I have some time if it does not work.

If you don't see anything there, one way of checking if it works is, from the repo:
`python3 NordIndicator.py`
And there should be some error there.

**Comment by TheLoving** [comment]
Yes it showed up. It is not available under widgets. But when I searched, it showed and was added to panel automatically.

But the icons looks somewhat blur.
![Screenshot_20210623_235126](https://user-images.githubusercontent.com/81813176/123148518-f583fb00-d47d-11eb-9ec5-28847842a1a6.png)

**Comment by TheLoving** [comment]
Anyway it is fixed so I will close the issue.

**Comment by dvilelaf** [comment]
Thank you for reporting this and helping with the debugging. Does it work properly? The blurry icon, I guess, could be due to some re-scalation. May be I'll try to use a SVG file instead of a PNG.

**Comment by TheLoving** [comment]
It is working fine. Only icon is blurry (borders to be precise). I did try disconnecting and reconnecting, working fully and Thank You for this.

**Comment by dvilelaf** [comment]
@TheLoving I've pushed a new branch "svg-icons", just in case you want to try and see if that solves the blurriness. In my case, the only difference I notice is that my icon is now smaller.

**Comment by TheLoving** [comment]
Yes, svg is perfect. No blur and its aligned nicely.

![Screenshot_20210625_001212](https://user-images.githubusercontent.com/81813176/123316242-3ea18100-d54a-11eb-899c-6439edfcb3ff.png)
