### ISSUE TITLE
The killProcessByTag() function is buggy

### ISSUE THREAD

**Issue by ntc2** [derkomai/NordIndicator#12]
The `killProcessByTag` function kills every process other than the current process that has `NordIndicator` in its command line. In particular, this kills any editor processes that were started via `<editor> NordIndicator.py`, e.g. it's killing my `emacs NordIndicator.py` process, which is making debugging the other issue I reported annoying :)

The `killProcessByTag` is only called in `uninstall`, and so I think it's sufficient to just get rid of this function and require the user to manually quit the indicator app before or after uninstalling. But if you want to keep this "kill existing indicator processes on uninstall" behavior, then I think a more robust approach would be to use PID files.

**Comment by dvilelaf** [comment]
I've just pushed a "fix" to both the issues (#11  & #12 ): now the installer won't auto-launch and the uninstaller won't auto-kill. You're right in that the implementations are buggy, so we'll let the user handle launching and closing.
