### ISSUE TITLE
Failed install on Mint/Cinnamon 20.3

### ISSUE THREAD

**Issue by xmanore** [derkomai/NordIndicator#13]
Error message:

user@system:~/Downloads/activeapps/NordIndicator$ python3 NordIndicator.py install
  File "NordIndicator.py", line 8
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
user@system:~/Downloads/activeapps/NordIndicator$ 
![Screenshot from 2022-06-24 09-15-22](https://user-images.githubusercontent.com/36577170/175575749-bf99e1b7-b237-40a5-8f0a-1e4a5682eee8.png)

**Comment by dvilelaf** [comment]
How did you download Nordindicator? It looks like you are trying to install a wrong file that contains HTML code and not an actual python file.

**Comment by xmanore** [comment]
> How did you download Nordindicator? It looks like you are trying to install a wrong file that contains HTML code and not an actual python file.

Got the file here:
![Screenshot from 2022-06-24 09-34-31](https://user-images.githubusercontent.com/36577170/175588139-0ba69345-3526-43c2-9b9f-eedc2fef57d7.png)

**Comment by dvilelaf** [comment]
You should download it from [here](https://github.com/dvilelaf/NordIndicator). Click on the green button at the top that says "Code" and then in download zip. You'll need to unzip/extract it and then you'll see a folder with the correct code.

**Comment by dvilelaf** [comment]
Other way: go [here](https://raw.githubusercontent.com/dvilelaf/NordIndicator/main/NordIndicator.py), right click the file and download it.

**Comment by xmanore** [comment]
Done.  Thanks for helping out the helpless!!!
