### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by klangfarben1** [derkomai/NordIndicator#2]
In Manjaro/KDE I'm getting the following error when trying to install. I did grab the latest variable fix.

NordIndicator-main]$ python3 NordIndicator.py install
python3: can't open file '/home/"xxx"/Downloads/NordIndicator-main/NordIndicator.py': [Errno 2] No such file or directory
("xxx" is username)

**Comment by dvilelaf** [comment]
Thank you for reporting this. Could you also try this and paste the result? https://github.com/derkomai/NordIndicator/issues/1#issuecomment-867016636

**Comment by klangfarben1** [comment]
Sure, here are the results.

file: /home/xxx/Downloads/Test.py
appName: /home/xxx/Downloads/Test
homeDir: /home/xxx
srcDir: /home/xxx/Downloads/Test.py
srcIconDir: /home/xxx/Downloads/Test.py/icons

**Comment by TheLoving** [comment]
Are you sure you have latest commit? Because test.py/icons shows the error I faced earlier.

Do one thing, clone this repo again into a folder (in Downloads/Nord) and re-check.

**Comment by klangfarben1** [comment]
Sure, one sec. 

Is the appName in the second line correct or should it be /home/xxx/Downloads/Test.py instead?

**Comment by TheLoving** [comment]
App name is right, he replaced **.py** with empty string.

**Comment by TheLoving** [comment]
The output you got is right one. I also tried and got same.

Maybe a clean clone will fix the issue.

**Comment by klangfarben1** [comment]
Cloning worked and I can add it to the panel tray. Icons are not displaying though. Will try and sort that out. But this issue can be closed now.

**Comment by TheLoving** [comment]
Which panel are you using latte or kde? In mine it is displaying.

**Comment by TheLoving** [comment]
Or check check inside the **system tray entries**, maybe there it was disabled.

**Comment by klangfarben1** [comment]
Looking at my .local/share directory, the install did not copy anything into .local/share/icons

**Comment by TheLoving** [comment]
Try manually copying those 3 pngs into **.local/share/icons**

**Comment by klangfarben1** [comment]
Yep, I did and icons now display correctly.

**Comment by TheLoving** [comment]
I think, the Issue is in the copy statement.

**Comment by dvilelaf** [comment]
Please run this new script @klangfarben1 . It seems some directory has still a wrong value. 

```
import os
import getpass

appName = (__file__.split('/')[-1] if '/' in __file__ else __file__).replace('.py', '')
homeDir = f'/home/{getpass.getuser()}'
srcDir = os.path.realpath(__file__).replace(f'/{appName}.py', '')
srcIconDir = f'{srcDir}/icons'
dstBinDir = f'{homeDir}/.local/bin'
dstIconDir = f'{homeDir}/.local/share/icons'
dstAppDir = f'{homeDir}/.local/share/applications'
dstAutostartDir = f'{homeDir}/.config/autostart'

print(f'file: {__file__}\n' \
      f'appName: {appName}\n' \
      f'homeDir: {homeDir}\n' \
      f'srcDir: {srcDir}\n' \
      f'srcIconDir: {srcIconDir}\n' \
      f'dstBinDir: {dstBinDir}\n' \
      f'dstIconDir: {dstIconDir}\n' \
      f'dstAppDir: {dstAppDir}\n' \
      f'dstAutostartDir: {dstAutostartDir}')
```
