### ISSUE TITLE
install on mint Cinnamon 20.1 (dependency on shared icons?)

### ISSUE THREAD

**Issue by captchrisr** [derkomai/NordIndicator#5]
$ python3 NordIndicator.py install
Traceback (most recent call last):
  File "NordIndicator.py", line 638, in <module>
    installation.install()
  File "NordIndicator.py", line 456, in install
    self.generateIcons()
  File "NordIndicator.py", line 598, in generateIcons
    with open(f'{self.dstIconDir}/{iconName}.svg', 'w') as iconFile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/chris/.local/share/icons/vpn_on.svg'

**Comment by Spitfireap** [comment]
@derkomai maybe icons should be stored in .config/NordIndicator? 😄

**Comment by captchrisr** [comment]
I'll take a look. Thanks

**Comment by dvilelaf** [comment]
@captchrisr Could you try the new version I just pushed? It seems some distributions use `~/.icons` instead of `~/.local/share/icons `according to the [standard](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout).
