### ISSUE TITLE
Disconnect option doesn't disconnect

### ISSUE THREAD

**Issue by xmanore** [derkomai/NordIndicator#9]
Running NordIndicator on Linux Mint 20.3 Una.  LOVE it.  Running Nord via terminal.

That's the extent of my knowledge...

When I click "disconnect", it doesnt.

**Comment by Spitfireap** [comment]
Hey, weird, working on my side on Arch. 
Could you stop NordIndicator, open a terminal, `cd ~/.local/bin` and execute `python3 NordIndicator.py`. This should start it on the tray, then try to disconnect and if you can then upload what the terminal is telling you :)

**Comment by dvilelaf** [comment]
Does running` nordvpn disconnect `on a terminal work for you?

**Comment by xmanore** [comment]
Hi,
Apologies for the late reply.  All seems to be working now.  Hiccup?  To answer your later question, yes - terminal connect/disconnect was working.

One question:  If I edit "Switzerland" to another country, do I have to make changes anywhere else in the script?

Thank you!!!

**Comment by dvilelaf** [comment]
>

> Hi, Apologies for the late reply. All seems to be working now. Hiccup? To answer your later question, yes - terminal connect/disconnect was working.
> 
> One question: If I edit "Switzerland" to another country, do I have to make changes anywhere else in the script?
> 
> Thank you!!!

You should only edit the `config.py` file, and make sure that the country you write is supported by NordVpn.

**Comment by xmanore** [comment]
I'll apologize ahead of time - I'm really dumb when it somes to these things...

Are you referring to the NordIndicator.py that I saved the script to? Or is there a config.py (there's a WHOLE BUNCH of them) somewhere else on my computer?

**Comment by Spitfireap** [comment]
Don't worry :). You can find the config file here : `~/.config/NordIndicator/config.py`. You can then edit country1 and/or country2. To check available country and to avoid typo, you can open a terminal and write `nordvpn countries` :)

**Comment by ntc2** [comment]
See #11.
